FROM ruby:2.3.0

RUN apt-get update && apt-get install -y \ 
  build-essential \ 
  nodejs

RUN apt-get dist-upgrade -y

# Add options to gemrc
RUN echo "gem: --no-document" > ~/.gemrc

RUN mkdir /app
WORKDIR /app

ADD Gemfile Gemfile.lock ./
RUN gem install bundler && bundle install --jobs 20 --retry 5

ADD . ./

EXPOSE 3000